<?php
require_once dirname(__DIR__).'/includes/bootstrap.php'; require_module('budget');
$pageTitle='Add Budget'; $activeMenu='budget-add'; $errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){ verify_csrf();
 $year=(int)($_POST['budget_year']??date('Y')); $dept=(int)($_POST['department_id']??0); $cat=(int)($_POST['category_id']??0); $desc=trim($_POST['description']??''); $amount=(float)($_POST['allocated_amount']??0);
 if($year<2020||$year>2100)$errors[]='Budget year is invalid.'; if(!$dept)$errors[]='Department is required.'; if(!$cat)$errors[]='Category is required.'; if($desc==='')$errors[]='Description is required.'; if($amount<=0)$errors[]='Allocated amount must be greater than zero.';
 if(!$errors){ $code=generate_code('BUD','budgets','budget_code'); db()->beginTransaction(); try{ $s=db()->prepare("INSERT INTO budgets(budget_code,budget_year,department_id,category_id,description,allocated_amount,approval_status,created_by) VALUES(?,?,?,?,?,?,'Pending',?)");$s->execute([$code,$year,$dept,$cat,$desc,$amount,current_user()['id']]);$id=(int)db()->lastInsertId(); save_approval_request('budget',$id); db()->commit(); log_activity('CREATE','Budget','Created '.$code); flash('success','Budget created and submitted for approval.'); redirect('budget/index.php'); }catch(Throwable $e){db()->rollBack();$errors[]='Unable to create budget: '.$e->getMessage();}}
}
$departments=departments();$categories=categories(); require ROOT_PATH.'/includes/header.php'; ?>
<div class="page-head"><div><h1>Add Budget</h1><p>Create a budget allocation and submit it into the approval workflow.</p></div><a href="<?= e(url('budget/index.php')) ?>" class="btn btn-light border"><i class="fa-solid fa-arrow-left me-2"></i>Back</a></div>
<?php if($errors): ?><div class="alert alert-danger"><ul class="mb-0"><?php foreach($errors as $x): ?><li><?= e($x) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
<div class="row"><div class="col-xl-9"><div class="card-panel"><div class="card-head"><h2 class="section-title">Budget Information</h2><span class="badge bg-warning-subtle text-warning">New Request</span></div><div class="card-body"><form method="post"><?= csrf_field() ?><div class="row g-3"><div class="col-md-4"><label class="form-label">Budget Year</label><input class="form-control" type="number" name="budget_year" min="2020" max="2100" value="<?= e($_POST['budget_year']??date('Y')) ?>" required></div><div class="col-md-4"><label class="form-label">Department</label><select class="form-select" name="department_id" required><option value="">Select department</option><?php foreach($departments as $d): ?><option value="<?= $d['id'] ?>" <?= (($_POST['department_id']??'')==$d['id'])?'selected':'' ?>><?= e($d['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Budget Category</label><select class="form-select" name="category_id" required><option value="">Select category</option><?php foreach($categories as $c): ?><option value="<?= $c['id'] ?>" <?= (($_POST['category_id']??'')==$c['id'])?'selected':'' ?>><?= e($c['name']) ?></option><?php endforeach; ?></select></div><div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="description" rows="4" required><?= e($_POST['description']??'') ?></textarea></div><div class="col-md-6"><label class="form-label">Allocated Amount (PHP)</label><input class="form-control" type="number" step="0.01" min="0.01" name="allocated_amount" value="<?= e($_POST['allocated_amount']??'') ?>" required></div><div class="col-12 pt-2"><button class="btn btn-primary px-4"><i class="fa-solid fa-paper-plane me-2"></i>Save & Submit</button></div></div></form></div></div></div><div class="col-xl-3 mt-3 mt-xl-0"><div class="info-banner"><strong><i class="fa-solid fa-circle-info me-2"></i>Workflow</strong><div class="small mt-2">The new budget starts as <b>Pending</b>, moves to department manager review, then Finance approval before it is included in approved budget totals.</div></div></div></div>
<?php require ROOT_PATH.'/includes/footer.php'; ?>
