<?php
require_once dirname(__DIR__) . '/includes/bootstrap.php';
require_module('dashboard');
$pageTitle='Executive Dashboard'; $activeMenu='dashboard';
$totalBudget=scalar("SELECT COALESCE(SUM(allocated_amount),0) FROM budgets WHERE approval_status='Approved' AND budget_year=YEAR(CURDATE())");
$totalExpenses=scalar("SELECT COALESCE(SUM(amount),0) FROM expenses WHERE status='Approved' AND YEAR(expense_date)=YEAR(CURDATE())");
$remaining=$totalBudget-$totalExpenses;
$util=$totalBudget>0?($totalExpenses/$totalBudget*100):0;
$pending=scalar("SELECT COUNT(*) FROM approvals WHERE status='Pending'");

$monthly=db()->query("SELECT DATE_FORMAT(expense_date,'%b') label, MONTH(expense_date) m, SUM(amount) total FROM expenses WHERE status='Approved' AND YEAR(expense_date)=YEAR(CURDATE()) GROUP BY MONTH(expense_date), DATE_FORMAT(expense_date,'%b') ORDER BY m")->fetchAll();
$alloc=db()->query("SELECT c.name label, SUM(b.allocated_amount) total FROM budgets b JOIN budget_categories c ON c.id=b.category_id WHERE b.approval_status='Approved' AND b.budget_year=YEAR(CURDATE()) GROUP BY c.id,c.name ORDER BY total DESC LIMIT 8")->fetchAll();
$budgetVs=db()->query("SELECT d.name label, COALESCE(SUM(b.allocated_amount),0) budget, COALESCE((SELECT SUM(e.amount) FROM expenses e WHERE e.department_id=d.id AND e.status='Approved' AND YEAR(e.expense_date)=YEAR(CURDATE())),0) expenses FROM departments d LEFT JOIN budgets b ON b.department_id=d.id AND b.approval_status='Approved' AND b.budget_year=YEAR(CURDATE()) GROUP BY d.id,d.name ORDER BY d.name")->fetchAll();
$sales=db()->query("SELECT CONCAT(u.first_name,' ',u.last_name) person, SUM(sr.actual_sales) actual, SUM(sr.sales_target) target FROM sales_records sr JOIN users u ON u.id=sr.salesperson_id WHERE YEAR(sr.sales_month)=YEAR(CURDATE()) GROUP BY u.id,u.first_name,u.last_name ORDER BY actual DESC LIMIT 5")->fetchAll();
$salesTarget=scalar("SELECT COALESCE(SUM(sales_target),0) FROM sales_records WHERE YEAR(sales_month)=YEAR(CURDATE())");
$salesActual=scalar("SELECT COALESCE(SUM(actual_sales),0) FROM sales_records WHERE YEAR(sales_month)=YEAR(CURDATE())");
$salesAchievement=$salesTarget>0?($salesActual/$salesTarget*100):0;
$recentTx=db()->query("SELECT e.expense_code code,e.expense_date dt,e.description,e.amount,e.status,d.name department FROM expenses e JOIN departments d ON d.id=e.department_id ORDER BY e.id DESC LIMIT 7")->fetchAll();
$recentApprovals=db()->query("SELECT a.id,a.request_type,a.current_stage,a.status,a.created_at, CONCAT(u.first_name,' ',u.last_name) submitter FROM approvals a JOIN users u ON u.id=a.submitted_by ORDER BY a.id DESC LIMIT 6")->fetchAll();
require ROOT_PATH.'/includes/header.php';
?>
<div class="page-head"><div><h1>Executive Dashboard</h1><p>Financial and commercial performance overview for <?= e(date('Y')) ?>.</p></div><div class="d-flex gap-2"><?php if(can_access('reports')): ?><a href="<?= e(url('reports/index.php')) ?>" class="btn btn-light border"><i class="fa-solid fa-file-export me-2"></i>Reports</a><?php endif; ?><?php if(can_access('expenses')): ?><a href="<?= e(url('expenses/create.php')) ?>" class="btn btn-primary"><i class="fa-solid fa-plus me-2"></i>New Expense</a><?php endif; ?></div></div>
<div class="row g-3 mb-4">
  <div class="col-12 col-sm-6 col-xl-3"><div class="kpi-card"><div class="kpi-top"><div><div class="kpi-label">Total Budget</div><div class="kpi-value"><?= money($totalBudget) ?></div></div><div class="kpi-icon blue"><i class="fa-solid fa-wallet"></i></div></div><div class="kpi-meta">Approved budget allocation</div></div></div>
  <div class="col-12 col-sm-6 col-xl-3"><div class="kpi-card"><div class="kpi-top"><div><div class="kpi-label">Total Expenses</div><div class="kpi-value"><?= money($totalExpenses) ?></div></div><div class="kpi-icon orange"><i class="fa-solid fa-receipt"></i></div></div><div class="kpi-meta">Approved expenditures</div></div></div>
  <div class="col-12 col-sm-6 col-xl-3"><div class="kpi-card"><div class="kpi-top"><div><div class="kpi-label">Remaining Balance</div><div class="kpi-value"><?= money($remaining) ?></div></div><div class="kpi-icon green"><i class="fa-solid fa-piggy-bank"></i></div></div><div class="kpi-meta"><?= $remaining>=0?'Within available funding':'Budget overrun detected' ?></div></div></div>
  <div class="col-12 col-sm-6 col-xl-3"><div class="kpi-card"><div class="kpi-top"><div><div class="kpi-label">Budget Utilization</div><div class="kpi-value"><?= number_format($util,1) ?>%</div></div><div class="kpi-icon purple"><i class="fa-solid fa-chart-simple"></i></div></div><div class="stat-progress mt-2"><span style="width:<?= min(100,$util) ?>%"></span></div><div class="kpi-meta mt-2"><?= (int)$pending ?> requests pending approval</div></div></div>
</div>
<div class="row g-3 mb-4">
 <div class="col-xl-7"><div class="card-panel h-100"><div class="card-head"><h2 class="section-title">Budget vs Expenses by Department</h2><span class="badge bg-primary-subtle text-primary">YTD</span></div><div class="card-body"><div class="chart-box"><canvas id="budgetExpenseChart"></canvas></div></div></div></div>
 <div class="col-xl-5"><div class="card-panel h-100"><div class="card-head"><h2 class="section-title">Budget Allocation</h2><span class="text-secondary small">By category</span></div><div class="card-body"><div class="chart-box"><canvas id="allocationChart"></canvas></div></div></div></div>
</div>
<div class="row g-3 mb-4">
 <div class="col-xl-7"><div class="card-panel"><div class="card-head"><h2 class="section-title">Monthly Expense Trend</h2><span class="text-secondary small"><?= e(date('Y')) ?></span></div><div class="card-body"><div class="chart-box"><canvas id="expenseTrendChart"></canvas></div></div></div></div>
 <div class="col-xl-5"><div class="card-panel h-100"><div class="card-head"><h2 class="section-title">Sales Performance</h2><?php if(can_access('sales')): ?><a href="<?= e(url('sales/index.php')) ?>" class="small text-decoration-none">View sales</a><?php endif; ?></div><div class="card-body"><div style="height:170px" class="mb-2"><canvas id="salesProgressChart"></canvas></div><div class="text-center mb-3"><strong class="fs-5"><?= number_format($salesAchievement,1) ?>%</strong><div class="small text-secondary">YTD target achievement</div></div><?php if(!$sales): ?><div class="empty-state py-3">No sales records yet.</div><?php else: foreach(array_slice($sales,0,3) as $i=>$s): $a=$s['target']>0?$s['actual']/$s['target']*100:0; ?><div class="metric-row"><div><strong>#<?= $i+1 ?> <?= e($s['person']) ?></strong><div class="small text-secondary"><?= money($s['actual']) ?> actual</div></div><div class="text-end"><strong><?= number_format($a,1) ?>%</strong></div></div><?php endforeach; endif; ?></div></div></div>
</div>
<div class="row g-3">
 <div class="col-xl-7"><div class="card-panel"><div class="card-head"><h2 class="section-title">Recent Transactions</h2><?php if(can_access('expenses')): ?><a class="small text-decoration-none" href="<?= e(url('expenses/index.php')) ?>">View all</a><?php endif; ?></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Code</th><th>Date</th><th>Department</th><th>Description</th><th class="text-end">Amount</th><th>Status</th></tr></thead><tbody><?php foreach($recentTx as $r): ?><tr><td class="fw-semibold"><?= e($r['code']) ?></td><td><?= e(date('M d',strtotime($r['dt']))) ?></td><td><?= e($r['department']) ?></td><td><?= e($r['description']) ?></td><td class="text-end"><?= money($r['amount']) ?></td><td><?= status_badge($r['status']) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
 <div class="col-xl-5"><div class="card-panel"><div class="card-head"><h2 class="section-title">Recent Approvals</h2><?php if(can_access('approvals')): ?><a class="small text-decoration-none" href="<?= e(url('approvals/index.php')) ?>">Open queue</a><?php endif; ?></div><div class="card-body"><?php foreach($recentApprovals as $a): ?><div class="metric-row"><div><strong><?= e(ucfirst($a['request_type'])) ?> Request #<?= (int)$a['id'] ?></strong><div class="small text-secondary"><?= e($a['submitter']) ?> · <?= e(str_replace('_',' ',ucwords($a['current_stage'],'_'))) ?></div></div><?= status_badge($a['status']) ?></div><?php endforeach; ?></div></div></div>
</div>
<?php
$pageScripts='<script>
const budgetVs='.json_encode($budgetVs).'; const monthly='.json_encode($monthly).'; const alloc='.json_encode($alloc).'; const salesProgress={target:' . json_encode($salesTarget) . ',actual:' . json_encode($salesActual) . '};
new Chart(document.getElementById("budgetExpenseChart"),{type:"bar",data:{labels:budgetVs.map(x=>x.label),datasets:[{label:"Budget",data:budgetVs.map(x=>x.budget),backgroundColor:"#2563eb",borderRadius:6},{label:"Expenses",data:budgetVs.map(x=>x.expenses),backgroundColor:"#f59e0b",borderRadius:6}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"bottom"}},scales:{y:{beginAtZero:true}}}});
new Chart(document.getElementById("expenseTrendChart"),{type:"line",data:{labels:monthly.map(x=>x.label),datasets:[{label:"Expenses",data:monthly.map(x=>x.total),borderColor:"#2563eb",backgroundColor:"rgba(37,99,235,.10)",fill:true,tension:.35,pointRadius:4}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true}}}});
new Chart(document.getElementById("allocationChart"),{type:"doughnut",data:{labels:alloc.map(x=>x.label),datasets:[{data:alloc.map(x=>x.total),backgroundColor:["#2563eb","#16a34a","#f59e0b","#7c3aed","#06b6d4","#ef4444","#64748b","#84cc16"],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:"68%",plugins:{legend:{position:"bottom"}}}});
const remainingSales=Math.max(0,salesProgress.target-salesProgress.actual); new Chart(document.getElementById("salesProgressChart"),{type:"doughnut",data:{labels:["Actual Sales","Remaining Target"],datasets:[{data:[salesProgress.actual,remainingSales],backgroundColor:["#16a34a","#e8edf3"],borderWidth:0,circumference:240,rotation:240}]},options:{responsive:true,maintainAspectRatio:false,cutout:"74%",plugins:{legend:{display:false}}}});
</script>';
require ROOT_PATH.'/includes/footer.php';
?>
