<?php
require_once dirname(__DIR__).'/includes/bootstrap.php';require_module('sales');$pageTitle='Sales Dashboard';$activeMenu='sales-dashboard';$year=(int)($_GET['year']??date('Y'));
$totals=db()->prepare("SELECT COALESCE(SUM(sales_target),0) target,COALESCE(SUM(actual_sales),0) actual FROM sales_records WHERE YEAR(sales_month)=?");$totals->execute([$year]);$t=$totals->fetch();$achievement=$t['target']>0?$t['actual']/$t['target']*100:0;
$rank=db()->prepare("SELECT CONCAT(u.first_name,' ',u.last_name) person,d.name department,SUM(sr.sales_target) target,SUM(sr.actual_sales) actual FROM sales_records sr JOIN users u ON u.id=sr.salesperson_id LEFT JOIN departments d ON d.id=sr.department_id WHERE YEAR(sr.sales_month)=? GROUP BY u.id,u.first_name,u.last_name,d.name ORDER BY actual DESC");$rank->execute([$year]);$rank=$rank->fetchAll();
$monthly=db()->prepare("SELECT MONTH(sales_month) m,DATE_FORMAT(sales_month,'%b') label,SUM(sales_target) target,SUM(actual_sales) actual FROM sales_records WHERE YEAR(sales_month)=? GROUP BY MONTH(sales_month),DATE_FORMAT(sales_month,'%b') ORDER BY m");$monthly->execute([$year]);$monthly=$monthly->fetchAll();$top=$rank[0]??null;
require ROOT_PATH.'/includes/header.php';?>
<div class="page-head"><div><h1>Sales Performance Dashboard</h1><p>Target achievement, monthly comparison and salesperson ranking.</p></div><div class="d-flex gap-2"><form><select class="form-select" name="year" onchange="this.form.submit()"><?php for($y=date('Y')-3;$y<=date('Y')+1;$y++):?><option <?=$year==$y?'selected':''?>><?=$y?></option><?php endfor;?></select></form><a class="btn btn-primary" href="<?=e(url('sales/entry.php'))?>"><i class="fa-solid fa-plus me-2"></i>Sales Entry</a></div></div>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="kpi-card"><div class="kpi-label">Annual Sales Target</div><div class="kpi-value"><?=money($t['target'])?></div><div class="kpi-meta">Combined target for <?=$year?></div></div></div><div class="col-md-4"><div class="kpi-card"><div class="kpi-label">Actual Sales</div><div class="kpi-value"><?=money($t['actual'])?></div><div class="kpi-meta">Recorded realized sales</div></div></div><div class="col-md-4"><div class="kpi-card"><div class="kpi-label">Achievement</div><div class="kpi-value"><?=number_format($achievement,1)?>%</div><div class="stat-progress"><span style="width:<?=min(100,$achievement)?>%"></span></div><div class="kpi-meta mt-2"><?=$top?'Top: '.e($top['person']):'No ranking data yet'?></div></div></div></div>
<div class="row g-3"><div class="col-xl-7"><div class="card-panel"><div class="card-head"><h2 class="section-title">Monthly Target vs Actual</h2></div><div class="card-body"><div class="chart-box"><canvas id="salesChart"></canvas></div></div></div></div><div class="col-xl-5"><div class="card-panel"><div class="card-head"><h2 class="section-title">Sales Ranking</h2></div><div class="card-body"><?php if(!$rank):?><div class="empty-state">No sales records for <?=$year?>.</div><?php else:foreach(array_slice($rank,0,8) as $i=>$r):$a=$r['target']>0?$r['actual']/$r['target']*100:0;?><div class="metric-row"><div><strong>#<?=$i+1?> <?=e($r['person'])?></strong><div class="small text-secondary"><?=e($r['department']??'')?></div></div><div class="text-end"><strong><?=number_format($a,1)?>%</strong><div class="small text-secondary"><?=money($r['actual'])?></div></div></div><?php endforeach;endif;?></div></div></div></div>
<?php $pageScripts='<script>const sales='.json_encode($monthly).';new Chart(document.getElementById("salesChart"),{type:"bar",data:{labels:sales.map(x=>x.label),datasets:[{label:"Target",data:sales.map(x=>x.target),backgroundColor:"#dbeafe",borderColor:"#2563eb",borderWidth:1,borderRadius:6},{label:"Actual",data:sales.map(x=>x.actual),backgroundColor:"#16a34a",borderRadius:6}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"bottom"}},scales:{y:{beginAtZero:true}}}});</script>';require ROOT_PATH.'/includes/footer.php';?>
